print("Umar Mehmood")
print("Mahnoor")
print("Amna Noor")
print("Aiman Fatima")
print("Shazia Mustafa")
print("shoukat Mehmood")
print("2+3*4/5")
print("Kips teaching Methodolgy is very best")
print("Kips Discipline can not be Compromaise")
print("Kips Infrastructure is best")